### ISSUE TITLE
Add your original website to this repository

### ISSUE THREAD

**Issue by M8Crumble** [Powercoders-team/PowerCodersWebsite#1]
Please add the original website to this repository so we can merge the files.

**Comment by forestnestoris** [comment]
Ok, I'll create a new branch labeled original and copy the files

**Comment by M8Crumble** [comment]
... and the chat?

**Comment by M8Crumble** [comment]
Also, where is the source for the Power icon? I tried screenshotting it and putting it into the `redesign` branch (a new one) but it literally ruined everything.

**Comment by M8Crumble** [comment]
I have a discord now: https://discord.gg/EGFdk9j
