### ISSUE TITLE
something

### ISSUE THREAD

**Issue by M8Crumble** [Powercoders-team/PowerCodersWebsite#6]
There is another person on the _contributors_ page. Who is he/she? Why is he/she here?

**Comment by M8Crumble** [comment]
I'm talking about `vfridkin (Vlad)`.

**Comment by M8Crumble** [comment]
They're not in out Github Organisation.

**Comment by M8Crumble** [comment]
Kinda sus

**Comment by ConanPerson** [comment]
Maybe Ayana's father

**Comment by forestnestoris** [comment]
it is my dad
